import React from 'react';
import './Loading.css';
//<svg xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" style={{ margin: 'auto', background: 'none', display: 'block', shapeRendering: 'auto' }} width="211px" height="211px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
//    <circle cx={50} cy={50} fill="none" stroke="#5b63e1" strokeWidth={4} r={29} strokeDasharray="136.659280431156 47.553093477052">
//        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1.4492753623188404s" values="0 50 50;360 50 50" keyTimes="0;1" />
//    </circle>
//    {/* [ldio] generated by https://loading.io/ */}</svg>
const Loading = ({ isLoad }) => {
    return (
        <div className="ipl-progress-indicator" id="ipl-progress-indicator" style={{ opacity: isLoad ? .4 : 0 }}>
            <div className="ipl-progress-indicator-head">
                <div className="first-indicator" />
                <div className="second-indicator" />
            </div>
            <div className="insp-logo-frame">
                

            </div>
        </div>
    );
};

export default Loading;
